'use strict';var b,f="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function h(a,c){if(c){var d=g;a=a.split(".");for(var e=0;e<a.length-1;e++){var l=a[e];l in d||(d[l]={});d=d[l]}a=a[a.length-1];e=d[a];c=c(e);c!=e&&null!=c&&f(d,a,{configurable:!0,writable:!0,value:c})}}
h("Object.is",function(a){return a?a:function(a,d){return a===d?0!==a||1/a===1/d:a!==a&&d!==d}});h("String.prototype.includes",function(a){return a?a:function(a,d){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(a,d||0)}});var k=this;
function m(a,c){a=a.split(".");var d=k;a[0]in d||!d.execScript||d.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===c?d[e]&&d[e]!==Object.prototype[e]?d=d[e]:d=d[e]={}:d[e]=c}
function n(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c}function p(a){return"function"==n(a)};/*
 Copyright 2015 The Coding with Chrome Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 @author mbordihn@google.com (Markus Bordihn)
*/
function q(a,c,d,e){this.H=a;this.B=c;this.P=void 0===d?"":d;this.a=void 0===e?"":e}q.prototype.aa=function(){return this.H};q.prototype.getType=q.prototype.aa;q.prototype.W=function(){return this.B};q.prototype.getFunc=q.prototype.W;q.prototype.ca=function(){return this.P};q.prototype.getValue=q.prototype.ca;q.prototype.getName=function(){return this.a};q.prototype.getName=q.prototype.getName;function r(a){this.a={};this.g=void 0===a?!0:a;this.b=this.f=!1}
r.prototype.c=function(a,c){t(this,new q("cmd",a),c)};r.prototype.addCommand=r.prototype.c;r.prototype.I=function(a,c){t(this,new q("delay",null,a),c)};r.prototype.addDelay=r.prototype.I;r.prototype.clear=function(){this.a["default"]=[]};r.prototype.clear=r.prototype.clear;r.prototype.Ja=function(){};r.prototype.setTimerInterval=r.prototype.Ja;r.prototype.start=function(){this.f||(this.g=this.f=!0,this.b=!1,u(this))};r.prototype.start=r.prototype.start;
r.prototype.stop=function(a){this.f&&(this.b=this.g=this.f=!1,a&&"function"===typeof a&&a())};r.prototype.stop=r.prototype.stop;r.prototype.L=function(a){a=void 0===a?"default":a;return this.a[a]&&0<this.a[a].length?this.a[a].shift():null};r.prototype.getNext=r.prototype.L;r.prototype.Z=function(a){for(var c;c=this.L(a);)if("cmd"==c.H)return c.B;return null};r.prototype.getNextCommand=r.prototype.Z;function t(a,c,d){d=void 0===d?"default":d;d in a.a||(a.a[d]=[]);a.a[d].push(c);a.g&&a.start()}
function u(a){if(a.f&&!a.b)if(!("default"in a.a)||0>=a.a["default"].length)a.f=!1;else{var c=a.a["default"].shift(),d=c.H,e=c.P,c=c.B;switch(d){case "cmd":c&&"function"===typeof c&&(a.b=!0,c(e),a.b=!1,u(a));break;case "delay":a.b=!0;setTimeout(function(){this.b=!1;u(this)}.bind(a),e);break;default:console.error("Unknown Stack Type",d)}}};var v={CUSTOM:null,EDUCATOR:{type:"vehicle",j:54.5,l:28,h:90},TRACK3R:{type:"vehicle",j:32,l:20,h:157},"GRYO BOY":{type:"vehicle",j:54.5,l:30,h:75},"ROBOT ARM H25":{type:"arm",j:37.3,l:0,h:0}};function w(a,c,d){this.name="Runner Framework";this.b=null;this.a="";this.g={};this.s=void 0===c?null:c;this.f=void 0===a?null:a;this.i=void 0===d?null:d;this.o=new r;window.addEventListener("message",this.v.bind(this),!1);this.c("__handshake__",this.u.bind(this));this.c("__start__",this.A.bind(this));this.c("__ping__",this.w.bind(this))}m("cwc.framework.Runner",w);
w.prototype.c=function(a,c,d){d=void 0===d?this.s:d;a?c?this.g[a]=d?c.bind(d):c:console.error("Runner function "+a+" is undefined!"):console.error("Runner command is undefined!")};w.prototype.addCommand=w.prototype.c;w.prototype.U=function(a,c,d){a=a.includes(c);console.log((a?"Enable ":"Disable ")+d+" ...");this.send(d,{enable:a})};w.prototype.enableMonitor=w.prototype.U;
w.prototype.send=function(a,c,d){c=void 0===c?{}:c;d=void 0===d?0:d;this.b&&this.a?d?(this.o.c(function(){this.b.postMessage({command:a,value:c},this.a)}.bind(this)),this.o.I(d)):this.b.postMessage({command:a,value:c},this.a):console.error("Communication channel has not yet been opened")};w.prototype.send=w.prototype.send;w.prototype.Ca=function(a){a&&"function"===typeof a&&(this.f=a)};w.prototype.setCallback=w.prototype.Ca;w.prototype.Ga=function(a){a&&"function"===typeof a&&(this.i=a)};
w.prototype.setMonitor=w.prototype.Ga;w.prototype.T=function(a){a=void 0===a?"":a;console.log("Enable direct update.");this.send("__direct_update__",a)};w.prototype.enableDirectUpdate=w.prototype.T;w.prototype.v=function(a){if(!a)throw Error("Was not able to get browser event!");!this.b&&"source"in a&&(this.b=a.source);!this.a&&"origin"in a&&(this.a=a.origin);var c=a.data.command;a=a.data.value;if(c in this.g)this.g[c](a);else console.error("Command "+c+" is not defined yet")};
w.prototype.u=function(a){this.b&&this.a&&this.send("__handshake__",a)};w.prototype.A=function(){this.i&&(console.log("Initialize monitor ..."),this.i());this.f&&(console.log("Starting program ..."),this.f())};w.prototype.w=function(a){this.send("__pong__",{id:a,time:(new Date).getTime()})};function x(a){this.name="EV3 Framework";this.code=function(){a(this)}.bind(this);this.a=new w(this.code,this);this.o=this.v=this.A=this.N=this.s=this.b=function(){};this.R=this.w=this.M=this.O=this.u=0;this.g="";this.i=this.h=this.l=this.f=this.j=0;this.S=170/60;this.a.c("updateColorSensor",this.da);this.a.c("updateDeviceInfo",this.ea);this.a.c("updateGyroSensor",this.fa);this.a.c("updateIrSensor",this.ga);this.a.c("updateTouchSensor",this.ia);this.a.c("updateUltrasonicSensor",this.ja);this.a.c("updateRobotType",
this.ha);this.a.c("updateWheelDiameter",this.ka);this.a.c("updateWheelWidth",this.la);this.a.c("updateWheelbase",this.ma)}m("cwc.framework.Ev3",x);x.prototype.Ha=function(a){"custom"!=a&&(a in v?(console.log("Set robot model to "+a),this.C(v[a].type),this.D(v[a].j),this.F(v[a].l),this.G(v[a].h)):console.error("Unknown robot model: "+a))};x.prototype.setRobotModel=x.prototype.Ha;x.prototype.C=function(a){this.g=a;console.log("Set robot type to "+this.g)};x.prototype.setRobotType=x.prototype.C;
x.prototype.D=function(a){this.j=Number(a);this.f=this.j*Math.PI};x.prototype.setWheelDiameter=x.prototype.D;x.prototype.F=function(a){this.l=Number(a);y(this)};x.prototype.setWheelWidth=x.prototype.F;x.prototype.G=function(a){this.h=Number(a);y(this)};x.prototype.setWheelbase=x.prototype.G;function y(a){a.i=a.h?(a.h+a.l)*Math.PI:1}x.prototype.m=function(a,c){return Math.floor(a/360*Math.abs(100/(void 0===c?50:c))/this.S*1E3+250)};x.prototype.getDelay=x.prototype.m;x.prototype.V=function(){return this.u};
x.prototype.getColorSensorValue=x.prototype.V;x.prototype.X=function(){return this.w};x.prototype.getGyroSensorValue=x.prototype.X;x.prototype.Y=function(){return this.M};x.prototype.getIrSensorValue=x.prototype.Y;x.prototype.$=function(){return this.O};x.prototype.getTouchSensorValue=x.prototype.$;x.prototype.ba=function(){return this.R};x.prototype.getUltrasonicSensorValue=x.prototype.ba;x.prototype.sa=function(a){p(a)&&(this.s=a)};x.prototype.onColorSensorChange=x.prototype.sa;
x.prototype.ta=function(a){p(a)&&(this.v=a)};x.prototype.onGyroSensorChange=x.prototype.ta;x.prototype.ua=function(a){p(a)&&(this.A=a)};x.prototype.onIrSensorChange=x.prototype.ua;x.prototype.va=function(a){p(a)&&(this.N=a)};x.prototype.onTouchSensorChange=x.prototype.va;x.prototype.wa=function(a){p(a)&&(this.o=a)};x.prototype.onUltrasonicSensorChange=x.prototype.wa;x.prototype.La=function(){this.o=this.b};x.prototype.stopUltrasonicSensorEvent=x.prototype.La;
x.prototype.drawImage=function(a,c){this.a.send("drawImage",{file:a},c)};x.prototype.drawImage=x.prototype.drawImage;x.prototype.ya=function(a,c,d,e){this.a.send("playTone",{frequency:a,duration:c,volume:d},e)};x.prototype.playTone=x.prototype.ya;x.prototype.xa=function(a,c,d){this.a.send("playSound",{file:a,volume:c},d)};x.prototype.playSound=x.prototype.xa;x.prototype.qa=function(a,c,d){this.a.send("moveServo",{steps:a,speed:c},d)};x.prototype.moveServo=x.prototype.qa;
x.prototype.oa=function(a,c,d,e){this.a.send("movePen",{steps:a,speed:c,color:d},e)};x.prototype.movePen=x.prototype.oa;x.prototype.ra=function(a,c,d){"arm"==this.g?this.J(a,void 0,c,d):this.a.send("moveSteps",{distance:Math.round(a/360*this.f/10),steps:a,speed:c},!0===d?this.m(a,c):d)};x.prototype.moveSteps=x.prototype.ra;x.prototype.J=function(a,c,d,e){this.a.send("customMoveSteps",{steps:a,ports:c,speed:d},!0===e?this.m(a,d):e)};x.prototype.customMoveSteps=x.prototype.J;
x.prototype.na=function(a,c,d){var e=Math.round(10*a/this.f*360);this.a.send("moveSteps",{distance:a,steps:e,speed:c},!0===d?this.m(e,c):d)};x.prototype.moveDistance=x.prototype.na;x.prototype.Ba=function(a,c,d,e){this.a.send("rotateSteps",{steps:a,speed:c,ratio:d},e)};x.prototype.rotateSteps=x.prototype.Ba;x.prototype.za=function(a,c,d){if("arm"==this.g)this.K(a,void 0,c,d);else{var e=Math.round(this.i/360*a/this.f*360);this.a.send("rotateSteps",{angle:a,steps:e,speed:c},!0===d?this.m(e,c):d)}};
x.prototype.rotateAngle=x.prototype.za;x.prototype.K=function(a,c,d,e){var l=Math.round(this.i/360*a/this.f*360);this.a.send("customRotateSteps",{angle:a,steps:l,ports:c,speed:d},!0===e?this.m(l,d):e)};x.prototype.customRotateAngle=x.prototype.K;x.prototype.pa=function(a,c){this.a.send("movePower",{power:a},c)};x.prototype.movePower=x.prototype.pa;x.prototype.Aa=function(a,c,d){this.a.send("rotatePower",{power:a,opt_power:c},d)};x.prototype.rotatePower=x.prototype.Aa;
x.prototype.stop=function(a){this.a.send("stop",null,a)};x.prototype.stop=x.prototype.stop;x.prototype.Ma=function(a){this.a.send("wait",null,a)};x.prototype.wait=x.prototype.Ma;x.prototype.Da=function(a,c){this.a.send("setColorSensorMode",{mode:a},c)};x.prototype.setColorSensorMode=x.prototype.Da;x.prototype.Ea=function(a,c){this.a.send("setIrSensorMode",{mode:a},c)};x.prototype.setIrSensorMode=x.prototype.Ea;x.prototype.Ka=function(a,c){this.a.send("setUltrasonicSensorMode",{mode:a},c)};
x.prototype.setUltrasonicSensorMode=x.prototype.Ka;x.prototype.Fa=function(a,c,d){this.a.send("setLed",{color:a,mode:c},d)};x.prototype.setLed=x.prototype.Fa;x.prototype.Ia=function(a,c){this.a.send("setStepSpeed",{speed:a},c)};x.prototype.setStepSpeed=x.prototype.Ia;b=x.prototype;b.da=function(a){this.u=a;this.s(a)};b.ea=function(){};b.fa=function(a){this.w=a;this.v(a)};b.ga=function(a){this.M=a;this.A(a)};b.ia=function(a){this.O=a;this.N(a)};b.ja=function(a){this.R=a;this.o(a)};b.ha=function(a){this.C(a)};
b.ka=function(a){this.D(a)};b.la=function(a){this.F(a)};b.ma=function(a){this.G(a)};
