'use strict';var h="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)},m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function n(b,c){if(c){var d=m;b=b.split(".");for(var e=0;e<b.length-1;e++){var g=b[e];g in d||(d[g]={});d=d[g]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&h(d,b,{configurable:!0,writable:!0,value:c})}}
n("String.prototype.startsWith",function(b){return b?b:function(b,d){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var c=this+"";b+="";var g=c.length,f=b.length;d=Math.max(0,Math.min(d|0,c.length));for(var k=0;k<f&&d<g;)if(c[d++]!=b[k++])return!1;return k>=f}});
function aa(){aa=function(){};m.Symbol||(m.Symbol=ba)}var ca=0;function ba(b){return"jscomp_symbol_"+(b||"")+ca++}function p(){aa();var b=m.Symbol.iterator;b||(b=m.Symbol.iterator=m.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&h(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return da(this)}});p=function(){}}function da(b){var c=0;return ea(function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}})}
function ea(b){p();b={next:b};b[m.Symbol.iterator]=function(){return this};return b}function fa(b){p();var c=b[Symbol.iterator];return c?c.call(b):da(b)}
n("Promise",function(b){function c(b){this.b=0;this.h=void 0;this.a=[];var c=this.f();try{b(c.resolve,c.reject)}catch(l){c.reject(l)}}function d(){this.a=null}if(b)return b;d.prototype.b=function(b){this.a||(this.a=[],this.f());this.a.push(b)};d.prototype.f=function(){var b=this;this.c(function(){b.h()})};var e=m.setTimeout;d.prototype.c=function(b){e(b,0)};d.prototype.h=function(){for(;this.a&&this.a.length;){var b=this.a;this.a=[];for(var c=0;c<b.length;++c){var d=b[c];delete b[c];try{d()}catch(y){this.g(y)}}}this.a=
null};d.prototype.g=function(b){this.c(function(){throw b;})};c.prototype.f=function(){function b(b){return function(f){d||(d=!0,b.call(c,f))}}var c=this,d=!1;return{resolve:b(this.F),reject:b(this.g)}};c.prototype.F=function(b){if(b===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof c)this.K(b);else{a:switch(typeof b){case "object":var d=null!=b;break a;case "function":d=!0;break a;default:d=!1}d?this.D(b):this.s(b)}};c.prototype.D=function(b){var c=void 0;try{c=
b.then}catch(l){this.g(l);return}"function"==typeof c?this.R(c,b):this.s(b)};c.prototype.g=function(b){this.v(2,b)};c.prototype.s=function(b){this.v(1,b)};c.prototype.v=function(b,c){if(0!=this.b)throw Error("Cannot settle("+b+", "+c|"): Promise already settled in state"+this.b);this.b=b;this.h=c;this.C()};c.prototype.C=function(){if(this.a){for(var b=this.a,c=0;c<b.length;++c)b[c].call(),b[c]=null;this.a=null}};var g=new d;c.prototype.K=function(b){var c=this.f();b.c(c.resolve,c.reject)};c.prototype.R=
function(b,c){var d=this.f();try{b.call(c,d.resolve,d.reject)}catch(y){d.reject(y)}};c.prototype.then=function(b,d){function e(b,c){return"function"==typeof b?function(c){try{f(b(c))}catch(Aa){g(Aa)}}:c}var f,g,k=new c(function(b,c){f=b;g=c});this.c(e(b,f),e(d,g));return k};c.prototype.catch=function(b){return this.then(void 0,b)};c.prototype.c=function(b,c){function d(){switch(e.b){case 1:b(e.h);break;case 2:c(e.h);break;default:throw Error("Unexpected state: "+e.b);}}var e=this;this.a?this.a.push(function(){g.b(d)}):
g.b(d)};c.resolve=function(b){return b instanceof c?b:new c(function(c){c(b)})};c.reject=function(b){return new c(function(c,d){d(b)})};c.b=function(b){return new c(function(d,e){for(var g=fa(b),f=g.next();!f.done;f=g.next())c.resolve(f.value).c(d,e)})};c.a=function(b){var d=fa(b),e=d.next();return e.done?c.resolve([]):new c(function(b,g){function f(c){return function(d){k[c]=d;l--;l||b(k)}}var k=[],l=0;do k.push(void 0),l++,c.resolve(e.value).c(f(k.length-1),g),e=d.next();while(!e.done)})};c.$jscomp$new$AsyncExecutor=
function(){return new d};return c});var q=this;function ga(b,c){b=b.split(".");var d=q;b[0]in d||!d.execScript||d.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===c?d[e]&&d[e]!==Object.prototype[e]?d=d[e]:d=d[e]={}:d[e]=c}
function r(b){var c=typeof b;if("object"==c)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return c;var d=Object.prototype.toString.call(b);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof b.call)return"object";return c}function ha(b){var c=r(b);return"array"==c||"object"==c&&"number"==typeof b.length}function t(b){return"string"==typeof b}function u(b){var c=typeof b;return"object"==c&&null!=b||"function"==c}
function v(b,c){function d(){}d.prototype=c.prototype;b.W=c.prototype;b.prototype=new d;b.prototype.constructor=b;b.T=function(b,d,f){for(var e=Array(arguments.length-2),g=2;g<arguments.length;g++)e[g-2]=arguments[g];return c.prototype[d].apply(b,e)}};function w(b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var c=Error().stack;c&&(this.stack=c)}b&&(this.message=String(b))}v(w,Error);w.prototype.name="CustomError";var ia;function ja(b,c){for(var d=b.split("%s"),e="",g=Array.prototype.slice.call(arguments,1);g.length&&1<d.length;)e+=d.shift()+g.shift();return e+d.join("%s")}function x(b){if(!ka.test(b))return b;-1!=b.indexOf("&")&&(b=b.replace(la,"&amp;"));-1!=b.indexOf("<")&&(b=b.replace(ma,"&lt;"));-1!=b.indexOf(">")&&(b=b.replace(na,"&gt;"));-1!=b.indexOf('"')&&(b=b.replace(oa,"&quot;"));-1!=b.indexOf("'")&&(b=b.replace(pa,"&#39;"));-1!=b.indexOf("\x00")&&(b=b.replace(qa,"&#0;"));return b}
var la=/&/g,ma=/</g,na=/>/g,oa=/"/g,pa=/'/g,qa=/\x00/g,ka=/[\x00&<>"']/;function z(b,c){c.unshift(b);w.call(this,ja.apply(null,c));c.shift()}v(z,w);z.prototype.name="AssertionError";function ra(b,c){throw new z("Failure"+(b?": "+b:""),Array.prototype.slice.call(arguments,1));};var A=Array.prototype.forEach?function(b,c,d){Array.prototype.forEach.call(b,c,d)}:function(b,c,d){for(var e=b.length,g=t(b)?b.split(""):b,f=0;f<e;f++)f in g&&c.call(d,g[f],f,b)};function sa(b){var c=b.length;if(0<c){for(var d=Array(c),e=0;e<c;e++)d[e]=b[e];return d}return[]};var B;a:{var ta=q.navigator;if(ta){var ua=ta.userAgent;if(ua){B=ua;break a}}B=""};function va(b,c){for(var d in b)c.call(void 0,b[d],d,b)}var wa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function xa(b,c){for(var d,e,g=1;g<arguments.length;g++){e=arguments[g];for(d in e)b[d]=e[d];for(var f=0;f<wa.length;f++)d=wa[f],Object.prototype.hasOwnProperty.call(e,d)&&(b[d]=e[d])}};var ya=-1!=B.indexOf("Opera"),C=-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"),za=-1!=B.indexOf("Edge"),Ba=-1!=B.indexOf("Gecko")&&!(-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge"))&&!(-1!=B.indexOf("Trident")||-1!=B.indexOf("MSIE"))&&-1==B.indexOf("Edge"),Ca=-1!=B.toLowerCase().indexOf("webkit")&&-1==B.indexOf("Edge");function Da(){var b=q.document;return b?b.documentMode:void 0}var D;
a:{var E="",F=function(){var b=B;if(Ba)return/rv\:([^\);]+)(\)|;)/.exec(b);if(za)return/Edge\/([\d\.]+)/.exec(b);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(b);if(Ca)return/WebKit\/(\S+)/.exec(b);if(ya)return/(?:Version)[ \/]?(\S+)/.exec(b)}();F&&(E=F?F[1]:"");if(C){var G=Da();if(null!=G&&G>parseFloat(E)){D=String(G);break a}}D=E}var Ea;var Fa=q.document;Ea=Fa&&C?Da()||("CSS1Compat"==Fa.compatMode?parseInt(D,10):5):void 0;var H;(H=!C)||(H=9<=Number(Ea));var Ga=H;function I(){this.l="";this.a=Ha;this.o=null}I.prototype.B=!0;I.prototype.u=!0;I.prototype.toString=function(){return"SafeHtml{"+this.l+"}"};function J(b){if(b instanceof I&&b.constructor===I&&b.a===Ha)return b.l;ra("expected object of type SafeHtml, got '"+b+"' of type "+r(b));return"type_error:SafeHtml"}function Ia(b){if(b instanceof I)return b;var c=null;b.B&&(c=b.o);b=x(b.u?b.l:String(b));return K(b,c)}
function Ja(b){function c(b){"array"==r(b)?A(b,c):(b=Ia(b),e+=J(b),b=b.o,0==d?d=b:0!=b&&d!=b&&(d=null))}var d=0,e="";A(arguments,c);return K(e,d)}var Ha={};function K(b,c){var d=new I;d.l=b;d.o=c;return d}K("<!DOCTYPE html>",0);K("",0);var Ka=K("<br>",0);var La={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};function Ma(b,c){if(La[b.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+b.tagName+".");b.innerHTML=J(c)};function L(b){var c=document;return t(b)?c.getElementById(b):b}function Na(b,c){va(c,function(c,e){c&&c.u&&(c=c.l);"style"==e?b.style.cssText=c:"class"==e?b.className=c:"for"==e?b.htmlFor=c:Oa.hasOwnProperty(e)?b.setAttribute(Oa[e],c):e.lastIndexOf("aria-",0)&&e.lastIndexOf("data-",0)?b[e]=c:b.setAttribute(e,c)})}
var Oa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Pa(b,c,d){var e=arguments,g=document,f=String(e[0]),k=e[1];if(!Ga&&k&&(k.name||k.type)){f=["<",f];k.name&&f.push(' name="',x(k.name),'"');if(k.type){f.push(' type="',x(k.type),'"');var l={};xa(l,k);delete l.type;k=l}f.push(">");f=f.join("")}f=g.createElement(f);k&&(t(k)?f.className=k:"array"==r(k)?f.className=k.join(" "):Na(f,k));2<e.length&&Qa(g,f,e);return f}
function Qa(b,c,d){function e(d){d&&c.appendChild(t(d)?b.createTextNode(d):d)}for(var g=2;g<d.length;g++){var f=d[g];if(!ha(f)||u(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(u(f)){var k="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==r(f)){k="function"==typeof f.item;break a}}k=!1}A(k?sa(f):f,e)}}}function Ra(){this.a=q.document||document};var M={U:!0},Sa={V:!0};function N(){throw Error("Do not instantiate directly");}N.prototype.m=null;N.prototype.toString=function(){return this.content};function O(){N.call(this)}v(O,N);O.prototype.i=M;function P(b,c,d){b.innerHTML=Ta(c(d||Ua,void 0,void 0))}function Ta(b){if(!u(b))return String(b);if(b instanceof N){if(b.i===M)return b.content;if(b.i===Sa)return x(b.content)}ra("Soy template output is unsafe for use as HTML: "+b);return"zSoyz"}var Va=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,Ua={};function Wa(b){if(null!=b)switch(b.m){case 1:return 1;case -1:return-1;case 0:return 0}return null}function Q(b){return null!=b&&b.i===M?b:b instanceof I?R(J(b),b.o):R(x(String(String(b))),Wa(b))}var R=function(b){function c(b){this.content=b}c.prototype=b.prototype;return function(b,e){b=new c(String(b));void 0!==e&&(b.m=e);return b}}(O);(function(b){function c(b){this.content=b}c.prototype=b.prototype;return function(b,e){b=String(b);if(!b)return"";b=new c(b);void 0!==e&&(b.m=e);return b}})(O);
function S(b){return null!=b&&b.i===M?String(String(b.content).replace(Xa,"").replace(Ya,"&lt;")).replace(Za,$a):x(String(b))}var ab={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function $a(b){return ab[b]}
var Za=/[\x00\x22\x27\x3c\x3e]/g,Xa=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,Ya=/</g;function bb(b){return R('<dialog id="'+S(b.prefix)+'chrome"></dialog>')}bb.a="cwc.soy.Dialog.template";function T(b){var c=b.prefix,d=b.content;return R(U(b)+'<div id="'+S(c)+'content" class="_content">'+Q(d)+'</div><div id="'+S(c)+'buttons" class="_actions"><button id="'+S(c)+'close" type="button" class="_button _button--raised close">Close</button></div>')}T.a="cwc.soy.Dialog.contentTemplate";
function cb(b){var c=b.prefix,d=b.content;return R(U(b)+'<div class="_content">'+Q(d)+'</div><div class="_actions"><button id="'+S(c)+'ok" type="button" class="_button _button--raised _button--colored">OK</button></div>')}cb.a="cwc.soy.Dialog.alertTemplate";
function db(b){var c=b.prefix,d=b.content;return R(U(b)+'<div class="_content">'+Q(d)+'</div><div class="_actions"><button id="'+S(c)+'yes" type="button" class="_button _button--raised">Yes</button><button id="'+S(c)+'no" type="button" class="_button _button--raised close">No</button></div>')}db.a="cwc.soy.Dialog.yesNoTemplate";
function eb(b){var c=b.prefix,d=b.content,e=b.I;return R(U(b)+'<div class="_content '+S(c)+'prompt">'+(d?'<span class="'+S(c)+'prompt-content">'+Q(d)+"</span>":"")+'<div class="_textfield"><input class="_textfield__input" type="text" id="'+S(c)+'input" value="'+(e?S(e):"")+'"><label class="_textfield__label" for="'+S(c)+'input"></label></div></div><div class="_actions"><button id="'+S(c)+'ok" type="button" class="_button _button--raised _button--colored">Ok</button><button id="'+S(c)+'cancel" type="button" class="_button _button--raised close">Cancel</button></div>')}
eb.a="cwc.soy.Dialog.promptTemplate";function U(b){var c=b.title,d=b.G;b=b.H;return R('<h3 class="_title">'+(d?'<i class="material-icons">'+Q(d)+"</i>":"")+Q(c)+Q(b)+"</h3>")};/*
 Copyright 2015 The Coding with Chrome Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 @author mbordihn@google.com (Markus Bordihn)
*/
function V(){this.name="Dialog";this.prefix="cwc-dialog-";this.a=this.node=this.b=null;this.c=this.prefix+"chrome"}ga("cwc.utils.Dialog",V);V.prototype.show=function(){var b=W(this);b&&(X(this,b)||(b.show?b.show():b.setAttribute("open","")));Y()};V.prototype.show=V.prototype.show;V.prototype.showModal=function(){var b=W(this);b&&(X(this,b)||(b.showModal?b.showModal():b.setAttribute("open","")));Y()};V.prototype.showModal=V.prototype.showModal;
V.prototype.close=function(){var b=W(this);if(b&&X(this,b)){for(;b.firstChild;)b.removeChild(this.b.firstChild);b.close?b.close():b.removeAttribute("open")}};V.prototype.close=V.prototype.close;V.prototype.j=function(b,c,d,e){d=d?d:T;var g=W(this),f=b,k="",l="";"string"!==typeof b&&(f=b.title,k=b.icon||"",l=b.X||"");g&&(P(g,d,{content:c,prefix:this.prefix,title:f,G:k,H:l,I:e}),Y())};V.prototype.render=V.prototype.j;
V.prototype.N=function(b,c){W(this)&&(this.j(b,c,T),L(this.prefix+"close").addEventListener("click",this.close.bind(this)),this.showModal())};V.prototype.showContent=V.prototype.N;V.prototype.O=function(b,c,d){W(this)&&(this.j(b,"",T),b=L(this.prefix+"close"),P(L(this.prefix+"content"),c,d),b.addEventListener("click",this.close.bind(this)),this.showModal())};V.prototype.showTemplate=V.prototype.O;V.prototype.S=function(b,c){W(this)&&(P(L(this.prefix+"content"),b,c),Y())};
V.prototype.updateTemplate=V.prototype.S;V.prototype.A=function(b,c,d){b=Pa("button",{id:this.prefix+b,type:"button","class":"_button"},c);d&&b.addEventListener("click",d);L(this.prefix+"buttons").appendChild(b)};V.prototype.addButton=V.prototype.A;V.prototype.M=function(b,c){var d=this;return new Promise(function(e,g){W(d)?(d.j(b,c,cb),g=L(d.prefix+"ok"),g.addEventListener("click",d.close.bind(d)),d.a&&g.addEventListener("click",d.a),g.addEventListener("click",function(){e(!0)}),d.showModal()):g()})};
V.prototype.showAlert=V.prototype.M;V.prototype.w=function(b,c,d){var e=this;return new Promise(function(g,f){if(W(e)){e.j(b,c,eb,d);var k=L(e.prefix+"input"),l=L(e.prefix+"ok");l.addEventListener("click",e.close.bind(e));e.a&&l.addEventListener("click",e.a);l.addEventListener("click",function(){g(k.value)});k.addEventListener("keyup",function(b){13==b.keyCode&&l.click()});var y=L(e.prefix+"cancel");y.addEventListener("click",e.close.bind(e));y.addEventListener("click",f);e.showModal()}else f()})};
V.prototype.showPrompt=V.prototype.w;V.prototype.P=function(b,c){var d=this;return new Promise(function(e,g){W(d)?(d.j(b,c,db),g=L(d.prefix+"yes"),g.addEventListener("click",d.close.bind(d)),d.a&&g.addEventListener("click",d.a),g.addEventListener("click",function(){e(!0)}),g=L(d.prefix+"no"),g.addEventListener("click",d.close.bind(d)),g.addEventListener("click",function(){e(!1)}),d.showModal()):g()})};V.prototype.showYesNo=V.prototype.P;V.prototype.L=function(b){this.a=b};
V.prototype.setDefaultCloseHandler=V.prototype.L;function X(b,c){return(b=c||W(b))?b.hasAttribute("open"):!1}function Y(){"undefined"!==typeof window.a&&window.a.Y()}
function W(b){if(!b.b)if(L(b.c))b.b=L(b.c);else if(!L(b.c)){b.node=document.body||document.getElementsByTagName("body")[0];var c={prefix:b.prefix};var d=ia||(ia=new Ra);var c=bb(c||Ua),e=Ta(c);e.match(Va);if(c instanceof N)if(c.i===Sa)c=Ia(c.toString());else{if(c.i!==M)throw Error("Sanitized content was not of kind TEXT or HTML.");c=K(c.toString(),c.m||null)}else c=K(e,null);d=d.a;e=c;c=d.createElement("DIV");C?(Ma(c,Ja(Ka,e)),c.removeChild(c.firstChild)):Ma(c,e);if(1==c.childNodes.length)d=c.removeChild(c.firstChild);
else for(d=d.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);b.node&&d?b.node.appendChild(d):console.error("Unable to add dialog",d,"to node",b.node,"!");b.b=L(b.c)}return b.b};/*
 Copyright 2016 The Coding with Chrome Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 @author mbordihn@google.com (Markus Bordihn)
*/
function Z(){this.name="Python Framework";this.c=new V;this.a=""}ga("cwc.framework.Python",Z);
Z.prototype.J=function(){var b=document.getElementById("code").textContent.trim(),c=!1;b.startsWith("#!/usr/bin/python3")?c=!0:b.startsWith("#!/usr/bin/python2")&&(c=!1);Sk.canvas="canvas-chrome";Sk.configure({debugout:this.f.bind(this),inputfun:this.h.bind(this),inputfunTakesPrompt:!0,output:this.s.bind(this),uncaughtException:this.g.bind(this),python3:c,read:this.b});(Sk.TurtleGraphics||(Sk.TurtleGraphics={})).target="content";Sk.misceval.asyncToPromise(function(){return Sk.importMainWithBody("<stdin>",
!1,b,!0)}).then(function(){console.log("Done.")},function(b){console.error(b.toString())})};Z.prototype.run=Z.prototype.J;Z.prototype.f=function(b){b&&!/^\s+$/g.test(b)&&(this.a=b,console.debug(b))};Z.prototype.g=function(b){b&&!/^\s+$/g.test(b)&&(this.a=b,console.error(b))};Z.prototype.s=function(b){b&&!/^\s+$/g.test(b)&&(this.a=b,console.log(b))};Z.prototype.h=function(b){b=b||this.a||"";this.a="";return this.c.w("Input",b)};
Z.prototype.b=function(b){if(void 0===Sk.builtinFiles||void 0===Sk.builtinFiles.files[b])throw Error("File not found: '"+b+"'");return Sk.builtinFiles.files[b]};
