'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)},l="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(b,d){if(d){var c=l;b=b.split(".");for(var e=0;e<b.length-1;e++){var f=b[e];f in c||(c[f]={});c=c[f]}b=b[b.length-1];e=c[b];d=d(e);d!=e&&null!=d&&aa(c,b,{configurable:!0,writable:!0,value:d})}}
function ea(){ea=function(){};l.Symbol||(l.Symbol=fa)}var ga=0;function fa(b){return"jscomp_symbol_"+(b||"")+ga++}function ha(){ea();var b=l.Symbol.iterator;b||(b=l.Symbol.iterator=l.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&aa(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return ia(this)}});ha=function(){}}function ia(b){var d=0;return ja(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})}
function ja(b){ha();b={next:b};b[l.Symbol.iterator]=function(){return this};return b}function ka(b){ha();var d=b[Symbol.iterator];return d?d.call(b):ia(b)}
ba("Promise",function(b){function d(b){this.b=0;this.i=void 0;this.a=[];var c=this.g();try{b(c.resolve,c.reject)}catch(k){c.reject(k)}}function c(){this.a=null}if(b)return b;c.prototype.b=function(b){this.a||(this.a=[],this.g());this.a.push(b)};c.prototype.g=function(){var b=this;this.c(function(){b.i()})};var e=l.setTimeout;c.prototype.c=function(b){e(b,0)};c.prototype.i=function(){for(;this.a&&this.a.length;){var b=this.a;this.a=[];for(var c=0;c<b.length;++c){var d=b[c];delete b[c];try{d()}catch(n){this.h(n)}}}this.a=
null};c.prototype.h=function(b){this.c(function(){throw b;})};d.prototype.g=function(){function b(b){return function(e){d||(d=!0,b.call(c,e))}}var c=this,d=!1;return{resolve:b(this.S),reject:b(this.h)}};d.prototype.S=function(b){if(b===this)this.h(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.W(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?this.R(b):this.D(b)}};d.prototype.R=function(b){var c=void 0;try{c=
b.then}catch(k){this.h(k);return}"function"==typeof c?this.Z(c,b):this.D(b)};d.prototype.h=function(b){this.H(2,b)};d.prototype.D=function(b){this.H(1,b)};d.prototype.H=function(b,c){if(0!=this.b)throw Error("Cannot settle("+b+", "+c|"): Promise already settled in state"+this.b);this.b=b;this.i=c;this.P()};d.prototype.P=function(){if(this.a){for(var b=this.a,c=0;c<b.length;++c)b[c].call(),b[c]=null;this.a=null}};var f=new c;d.prototype.W=function(b){var c=this.g();b.c(c.resolve,c.reject)};d.prototype.Z=
function(b,c){var d=this.g();try{b.call(c,d.resolve,d.reject)}catch(n){d.reject(n)}};d.prototype.then=function(b,c){function e(b,c){return"function"==typeof b?function(c){try{g(b(c))}catch(P){f(P)}}:c}var g,f,h=new d(function(b,c){g=b;f=c});this.c(e(b,g),e(c,f));return h};d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.c=function(b,c){function d(){switch(e.b){case 1:b(e.i);break;case 2:c(e.i);break;default:throw Error("Unexpected state: "+e.b);}}var e=this;this.a?this.a.push(function(){f.b(d)}):
f.b(d)};d.resolve=function(b){return b instanceof d?b:new d(function(c){c(b)})};d.reject=function(b){return new d(function(c,d){d(b)})};d.b=function(b){return new d(function(c,e){for(var f=ka(b),g=f.next();!g.done;g=f.next())d.resolve(g.value).c(c,e)})};d.a=function(b){var c=ka(b),e=c.next();return e.done?d.resolve([]):new d(function(b,f){function g(c){return function(d){h[c]=d;k--;k||b(h)}}var h=[],k=0;do h.push(void 0),k++,d.resolve(e.value).c(g(h.length-1),f),e=c.next();while(!e.done)})};d.$jscomp$new$AsyncExecutor=
function(){return new c};return d});ba("Object.is",function(b){return b?b:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ba("String.prototype.includes",function(b){return b?b:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});var m=this;
function p(b){var d=typeof b;if("object"==d)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return d;var c=Object.prototype.toString.call(b);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==d&&"undefined"==typeof b.call)return"object";return d}function la(b){var d=p(b);return"array"==d||"object"==d&&"number"==typeof b.length}function q(b){return"string"==typeof b}function r(b){var d=typeof b;return"object"==d&&null!=b||"function"==d}function t(b,d){b=b.split(".");var c=m;b[0]in c||!c.execScript||c.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===d?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=d}
function ma(b,d){function c(){}c.prototype=d.prototype;b.pa=d.prototype;b.prototype=new c;b.prototype.constructor=b;b.ma=function(b,c,g){for(var e=Array(arguments.length-2),f=2;f<arguments.length;f++)e[f-2]=arguments[f];return d.prototype[c].apply(b,e)}};function u(b){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var d=Error().stack;d&&(this.stack=d)}b&&(this.message=String(b))}ma(u,Error);u.prototype.name="CustomError";var na;function oa(b,d){for(var c=b.split("%s"),e="",f=Array.prototype.slice.call(arguments,1);f.length&&1<c.length;)e+=c.shift()+f.shift();return e+c.join("%s")}function w(b){if(!pa.test(b))return b;-1!=b.indexOf("&")&&(b=b.replace(qa,"&amp;"));-1!=b.indexOf("<")&&(b=b.replace(ra,"&lt;"));-1!=b.indexOf(">")&&(b=b.replace(sa,"&gt;"));-1!=b.indexOf('"')&&(b=b.replace(ta,"&quot;"));-1!=b.indexOf("'")&&(b=b.replace(va,"&#39;"));-1!=b.indexOf("\x00")&&(b=b.replace(wa,"&#0;"));return b}
var qa=/&/g,ra=/</g,sa=/>/g,ta=/"/g,va=/'/g,wa=/\x00/g,pa=/[\x00&<>"']/;function xa(b){return String(b).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})}function ya(b){var d=q(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return b.replace(new RegExp("(^"+(d?"|["+d+"]+":"")+")([a-z])","g"),function(b,d,f){return d+f.toUpperCase()})};function za(b,d){d.unshift(b);u.call(this,oa.apply(null,d));d.shift()}ma(za,u);za.prototype.name="AssertionError";function Aa(b,d){throw new za("Failure"+(b?": "+b:""),Array.prototype.slice.call(arguments,1));};var Ba=Array.prototype.forEach?function(b,d,c){Array.prototype.forEach.call(b,d,c)}:function(b,d,c){for(var e=b.length,f=q(b)?b.split(""):b,g=0;g<e;g++)g in f&&d.call(c,f[g],g,b)};function Ca(b){var d=b.length;if(0<d){for(var c=Array(d),e=0;e<d;e++)c[e]=b[e];return c}return[]};var y;a:{var Da=m.navigator;if(Da){var Ea=Da.userAgent;if(Ea){y=Ea;break a}}y=""};function Fa(b,d){for(var c in b)d.call(void 0,b[c],c,b)}var Ga="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ha(b,d){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)b[c]=e[c];for(var g=0;g<Ga.length;g++)c=Ga[g],Object.prototype.hasOwnProperty.call(e,c)&&(b[c]=e[c])}};var Ia=-1!=y.indexOf("Opera"),z=-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"),Ja=-1!=y.indexOf("Edge"),Ka=-1!=y.indexOf("Gecko")&&!(-1!=y.toLowerCase().indexOf("webkit")&&-1==y.indexOf("Edge"))&&!(-1!=y.indexOf("Trident")||-1!=y.indexOf("MSIE"))&&-1==y.indexOf("Edge"),La=-1!=y.toLowerCase().indexOf("webkit")&&-1==y.indexOf("Edge");function Ma(){var b=m.document;return b?b.documentMode:void 0}var Na;
a:{var Oa="",Pa=function(){var b=y;if(Ka)return/rv\:([^\);]+)(\)|;)/.exec(b);if(Ja)return/Edge\/([\d\.]+)/.exec(b);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(b);if(La)return/WebKit\/(\S+)/.exec(b);if(Ia)return/(?:Version)[ \/]?(\S+)/.exec(b)}();Pa&&(Oa=Pa?Pa[1]:"");if(z){var Qa=Ma();if(null!=Qa&&Qa>parseFloat(Oa)){Na=String(Qa);break a}}Na=Oa}var Ra;var Sa=m.document;Ra=Sa&&z?Ma()||("CSS1Compat"==Sa.compatMode?parseInt(Na,10):5):void 0;var Ta;(Ta=!z)||(Ta=9<=Number(Ra));var Ua=Ta;function A(){this.o="";this.a=Va;this.A=null}A.prototype.O=!0;A.prototype.G=!0;A.prototype.toString=function(){return"SafeHtml{"+this.o+"}"};function Wa(b){if(b instanceof A&&b.constructor===A&&b.a===Va)return b.o;Aa("expected object of type SafeHtml, got '"+b+"' of type "+p(b));return"type_error:SafeHtml"}function Xa(b){if(b instanceof A)return b;var d=null;b.O&&(d=b.A);b=w(b.G?b.o:String(b));return B(b,d)}
function Ya(b){function d(b){"array"==p(b)?Ba(b,d):(b=Xa(b),e+=Wa(b),b=b.A,0==c?c=b:0!=b&&c!=b&&(c=null))}var c=0,e="";Ba(arguments,d);return B(e,c)}var Va={};function B(b,d){var c=new A;c.o=b;c.A=d;return c}B("<!DOCTYPE html>",0);B("",0);var Za=B("<br>",0);var $a={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};function ab(b,d){if($a[b.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+b.tagName+".");b.innerHTML=Wa(d)};function C(b){var d=document;return q(b)?d.getElementById(b):b}function bb(b,d){Fa(d,function(c,d){c&&c.G&&(c=c.o);"style"==d?b.style.cssText=c:"class"==d?b.className=c:"for"==d?b.htmlFor=c:cb.hasOwnProperty(d)?b.setAttribute(cb[d],c):d.lastIndexOf("aria-",0)&&d.lastIndexOf("data-",0)?b[d]=c:b.setAttribute(d,c)})}
var cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function db(b,d,c){var e=arguments,f=document,g=String(e[0]),h=e[1];if(!Ua&&h&&(h.name||h.type)){g=["<",g];h.name&&g.push(' name="',w(h.name),'"');if(h.type){g.push(' type="',w(h.type),'"');var k={};Ha(k,h);delete k.type;h=k}g.push(">");g=g.join("")}g=f.createElement(g);h&&(q(h)?g.className=h:"array"==p(h)?g.className=h.join(" "):bb(g,h));2<e.length&&eb(f,g,e,2);return g}
function eb(b,d,c,e){function f(c){c&&d.appendChild(q(c)?b.createTextNode(c):c)}for(;e<c.length;e++){var g=c[e];if(!la(g)||r(g)&&0<g.nodeType)f(g);else{a:{if(g&&"number"==typeof g.length){if(r(g)){var h="function"==typeof g.item||"string"==typeof g.item;break a}if("function"==p(g)){h="function"==typeof g.item;break a}}h=!1}Ba(h?Ca(g):g,f)}}}function fb(b,d){eb(9==b.nodeType?b:b.ownerDocument||b.document,b,arguments,1)}function gb(){this.a=m.document||document};var D={na:!0},hb={oa:!0};function E(){throw Error("Do not instantiate directly");}E.prototype.w=null;E.prototype.toString=function(){return this.content};function F(){E.call(this)}ma(F,E);F.prototype.j=D;function ib(b,d,c){b.innerHTML=jb(d(c||kb,void 0,void 0))}function jb(b){if(!r(b))return String(b);if(b instanceof E){if(b.j===D)return b.content;if(b.j===hb)return w(b.content)}Aa("Soy template output is unsafe for use as HTML: "+b);return"zSoyz"}var lb=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,kb={};function mb(b){if(null!=b)switch(b.w){case 1:return 1;case -1:return-1;case 0:return 0}return null}function G(b){return null!=b&&b.j===D?b:b instanceof A?H(Wa(b),b.A):H(w(String(String(b))),mb(b))}var H=function(b){function d(b){this.content=b}d.prototype=b.prototype;return function(b,e){b=new d(String(b));void 0!==e&&(b.w=e);return b}}(F);(function(b){function d(b){this.content=b}d.prototype=b.prototype;return function(b,e){b=String(b);if(!b)return"";b=new d(b);void 0!==e&&(b.w=e);return b}})(F);
function I(b){return null!=b&&b.j===D?String(String(b.content).replace(nb,"").replace(ob,"&lt;")).replace(pb,qb):w(String(b))}var rb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function qb(b){return rb[b]}
var pb=/[\x00\x22\x27\x3c\x3e]/g,nb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,ob=/</g;function sb(b){return H('<dialog id="'+I(b.prefix)+'chrome"></dialog>')}sb.a="cwc.soy.Dialog.template";function M(b){var d=b.prefix,c=b.content;return H(N(b)+'<div id="'+I(d)+'content" class="_content">'+G(c)+'</div><div id="'+I(d)+'buttons" class="_actions"><button id="'+I(d)+'close" type="button" class="_button _button--raised close">Close</button></div>')}M.a="cwc.soy.Dialog.contentTemplate";
function tb(b){var d=b.prefix,c=b.content;return H(N(b)+'<div class="_content">'+G(c)+'</div><div class="_actions"><button id="'+I(d)+'ok" type="button" class="_button _button--raised _button--colored">OK</button></div>')}tb.a="cwc.soy.Dialog.alertTemplate";
function ub(b){var d=b.prefix,c=b.content;return H(N(b)+'<div class="_content">'+G(c)+'</div><div class="_actions"><button id="'+I(d)+'yes" type="button" class="_button _button--raised">Yes</button><button id="'+I(d)+'no" type="button" class="_button _button--raised close">No</button></div>')}ub.a="cwc.soy.Dialog.yesNoTemplate";
function vb(b){var d=b.prefix,c=b.content,e=b.V;return H(N(b)+'<div class="_content '+I(d)+'prompt">'+(c?'<span class="'+I(d)+'prompt-content">'+G(c)+"</span>":"")+'<div class="_textfield"><input class="_textfield__input" type="text" id="'+I(d)+'input" value="'+(e?I(e):"")+'"><label class="_textfield__label" for="'+I(d)+'input"></label></div></div><div class="_actions"><button id="'+I(d)+'ok" type="button" class="_button _button--raised _button--colored">Ok</button><button id="'+I(d)+'cancel" type="button" class="_button _button--raised close">Cancel</button></div>')}
vb.a="cwc.soy.Dialog.promptTemplate";function N(b){var d=b.title,c=b.T;b=b.U;return H('<h3 class="_title">'+(c?'<i class="material-icons">'+G(c)+"</i>":"")+G(d)+G(b)+"</h3>")};/*
 Copyright 2015 The Coding with Chrome Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 @author mbordihn@google.com (Markus Bordihn)
*/
function O(){this.name="Dialog";this.prefix="cwc-dialog-";this.a=this.node=this.b=null;this.c=this.prefix+"chrome"}t("cwc.utils.Dialog",O);O.prototype.show=function(){var b=Q(this);b&&(wb(this,b)||(b.show?b.show():b.setAttribute("open","")));xb()};O.prototype.show=O.prototype.show;O.prototype.showModal=function(){var b=Q(this);b&&(wb(this,b)||(b.showModal?b.showModal():b.setAttribute("open","")));xb()};O.prototype.showModal=O.prototype.showModal;
O.prototype.close=function(){var b=Q(this);if(b&&wb(this,b)){for(;b.firstChild;)b.removeChild(this.b.firstChild);b.close?b.close():b.removeAttribute("open")}};O.prototype.close=O.prototype.close;O.prototype.l=function(b,d,c,e){c=c?c:M;var f=Q(this),g=b,h="",k="";"string"!==typeof b&&(g=b.title,h=b.icon||"",k=b.qa||"");f&&(ib(f,c,{content:d,prefix:this.prefix,title:g,T:h,U:k,V:e}),xb())};O.prototype.render=O.prototype.l;
O.prototype.L=function(b,d){Q(this)&&(this.l(b,d,M),C(this.prefix+"close").addEventListener("click",this.close.bind(this)),this.showModal())};O.prototype.showContent=O.prototype.L;O.prototype.Y=function(b,d,c){Q(this)&&(this.l(b,"",M),b=C(this.prefix+"close"),ib(C(this.prefix+"content"),d,c),b.addEventListener("click",this.close.bind(this)),this.showModal())};O.prototype.showTemplate=O.prototype.Y;O.prototype.$=function(b,d){Q(this)&&(ib(C(this.prefix+"content"),b,d),xb())};
O.prototype.updateTemplate=O.prototype.$;O.prototype.N=function(b,d,c){b=db("button",{id:this.prefix+b,type:"button","class":"_button"},d);c&&b.addEventListener("click",c);C(this.prefix+"buttons").appendChild(b)};O.prototype.addButton=O.prototype.N;O.prototype.B=function(b,d){var c=this;return new Promise(function(e,f){Q(c)?(c.l(b,d,tb),f=C(c.prefix+"ok"),f.addEventListener("click",c.close.bind(c)),c.a&&f.addEventListener("click",c.a),f.addEventListener("click",function(){e(!0)}),c.showModal()):f()})};
O.prototype.showAlert=O.prototype.B;O.prototype.u=function(b,d,c){var e=this;return new Promise(function(f,g){if(Q(e)){e.l(b,d,vb,c);var h=C(e.prefix+"input"),k=C(e.prefix+"ok");k.addEventListener("click",e.close.bind(e));e.a&&k.addEventListener("click",e.a);k.addEventListener("click",function(){f(h.value)});h.addEventListener("keyup",function(b){13==b.keyCode&&k.click()});var n=C(e.prefix+"cancel");n.addEventListener("click",e.close.bind(e));n.addEventListener("click",g);e.showModal()}else g()})};
O.prototype.showPrompt=O.prototype.u;O.prototype.v=function(b,d){var c=this;return new Promise(function(e,f){Q(c)?(c.l(b,d,ub),f=C(c.prefix+"yes"),f.addEventListener("click",c.close.bind(c)),c.a&&f.addEventListener("click",c.a),f.addEventListener("click",function(){e(!0)}),f=C(c.prefix+"no"),f.addEventListener("click",c.close.bind(c)),f.addEventListener("click",function(){e(!1)}),c.showModal()):f()})};O.prototype.showYesNo=O.prototype.v;O.prototype.X=function(b){this.a=b};
O.prototype.setDefaultCloseHandler=O.prototype.X;function wb(b,d){return(b=d||Q(b))?b.hasAttribute("open"):!1}function xb(){"undefined"!==typeof window.a&&window.a.ra()}
function Q(b){if(!b.b)if(C(b.c))b.b=C(b.c);else if(!C(b.c)){b.node=document.body||document.getElementsByTagName("body")[0];var d={prefix:b.prefix};var c=na||(na=new gb);var d=sb(d||kb),e=jb(d);e.match(lb);if(d instanceof E)if(d.j===hb)d=Xa(d.toString());else{if(d.j!==D)throw Error("Sanitized content was not of kind TEXT or HTML.");d=B(d.toString(),d.w||null)}else d=B(e,null);c=c.a;e=d;d=c.createElement("DIV");z?(ab(d,Ya(Za,e)),d.removeChild(d.firstChild)):ab(d,e);if(1==d.childNodes.length)c=d.removeChild(d.firstChild);
else for(c=c.createDocumentFragment();d.firstChild;)c.appendChild(d.firstChild);b.node&&c?b.node.appendChild(c):console.error("Unable to add dialog",c,"to node",b.node,"!");b.b=C(b.c)}return b.b};t("cwc.config.Debug",{ba:!1,da:!1,ha:!1,ca:!1,ja:!1,aa:!1,ia:!1,ea:!1,ka:!1,ga:!1,la:!1});t("cwc.config.Logging",{fa:6});function R(b){this.b=b;this.a=new O}t("cwc.framework.simple.Command",R);R.prototype.m=function(){return this.b||document.body};R.prototype.getTarget=R.prototype.m;R.prototype.write=function(b){b=document.createTextNode(String(b));var d=this.m();b&&d&&d.appendChild(b)};R.prototype.write=R.prototype.write;R.prototype.B=function(b,d){this.a.L(b,d)};R.prototype.showAlert=R.prototype.B;R.prototype.u=function(b,d,c){return this.a.u(b,d,c)};R.prototype.showPrompt=R.prototype.u;
R.prototype.v=function(b,d){return this.a.v(b,d)};R.prototype.showYesNo=R.prototype.v;R.prototype.s=function(){if(!window)throw Error("Window name space is not available in this instance.");window.command={write:this.write.bind(this),showAlert:this.B.bind(this),showPrompt:this.u.bind(this),showYesNo:this.v.bind(this)}};R.prototype.mapGlobal=R.prototype.s;var yb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};function zb(b){var d={};b=String(b);var c="#"==b.charAt(0)?b:"#"+b;if(Ab.test(c)){b=c;if(!Ab.test(b))throw Error("'"+b+"' is not a valid hex color");4==b.length&&(b=b.replace(Bb,"#$1$1$2$2$3$3"));d.f=b.toLowerCase();d.type="hex";return d}a:{var e=b.match(Cb);if(e){var c=Number(e[1]),f=Number(e[2]),e=Number(e[3]);if(0<=c&&255>=c&&0<=f&&255>=f&&0<=e&&255>=e){c=[c,f,e];break a}}c=[]}if(c.length)return d.f=Db(c[0],c[1],c[2]),d.type="rgb",d;if(yb&&(c=yb[b.toLowerCase()]))return d.f=c,d.type="named",d;
throw Error(b+" is not a valid color string");}var Bb=/#(.)(.)(.)/;function Db(b,d,c){b=Number(b);d=Number(d);c=Number(c);if(b!=(b&255)||d!=(d&255)||c!=(c&255))throw Error('"('+b+","+d+","+c+'") is not a valid RGB color');return"#"+S(b.toString(16))+S(d.toString(16))+S(c.toString(16))}function Eb(b,d,c){0>c?c+=1:1<c&&--c;return 1>6*c?b+6*(d-b)*c:1>2*c?d:2>3*c?b+(d-b)*(2/3-c)*6:b}var Ab=/^#(?:[0-9a-f]{3}){1,2}$/i,Cb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;
function S(b){return 1==b.length?"0"+b:b};function Fb(b){var d={};b=String(b);var c="#"==b.charAt(0)?b:"#"+b;if(Gb.test(c)){b=c;if(!Gb.test(b))throw Error("'"+b+"' is not a valid alpha hex color");5==b.length&&(b=b.replace(Hb,"#$1$1$2$2$3$3$4$4"));d.f=b.toLowerCase();d.type="hex";return d}a:{var e=b.match(Ib);if(e){var c=Number(e[1]),f=Number(e[2]);var g=Number(e[3]);e=Number(e[4]);if(0<=c&&255>=c&&0<=f&&255>=f&&0<=g&&255>=g&&0<=e&&1>=e){g=[c,f,g,e];break a}}g=[]}if(g.length){b=g[0];c=g[1];f=g[2];g=g[3];e=Math.floor(255*g);if(isNaN(e)||0>
e||255<e)throw Error('"('+b+","+c+","+f+","+g+'") is not a valid RGBA color');g=S(e.toString(16));b=Db(b,c,f)+g;d.f=b;d.type="rgba";return d}a:{if(e=b.match(Jb))if(c=Number(e[1]),f=Number(e[2]),g=Number(e[3]),e=Number(e[4]),0<=c&&360>=c&&0<=f&&100>=f&&0<=g&&100>=g&&0<=e&&1>=e){e=[c,f,g,e];break a}e=[]}if(e.length){c=e[0];g=e[1];f=e[2];b=e[3];e=Math.floor(255*b);if(isNaN(e)||0>e||255<e)throw Error('"('+c+","+g+","+f+","+b+'") is not a valid HSLA color');b=S(e.toString(16));g/=100;f/=100;c/=360;if(g){var e=
.5>f?f*(1+g):f+g-g*f;var h=2*f-e;f=255*Eb(h,e,c+1/3);g=255*Eb(h,e,c);c=255*Eb(h,e,c-1/3)}else f=g=c=255*f;c=[Math.round(f),Math.round(g),Math.round(c)];c=Db(c[0],c[1],c[2]);d.f=c+b;d.type="hsla";return d}throw Error(b+" is not a valid color string");}var Hb=/#(.)(.)(.)(.)/,Gb=/^#(?:[0-9a-f]{4}){1,2}$/i,Ib=/^(?:rgba)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|1|0\.\d{0,10})\)$/i,Jb=/^(?:hsla)\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\%,\s?(0|[1-9]\d{0,2})\%,\s?(0|1|0\.\d{0,10})\)$/i;function Kb(){this.b=!1;this.c=new T(void 0);this.h=new T(void 0);this.a=0;this.g=new T;this.i=new T}function U(b,d){b.h=new T(d)}function T(b){this.f=this.type="";if(null!=b)try{var d=zb(b);this.f=d.f;this.type=d.type}catch(c){b=Fb(b),this.f=b.f,this.type=b.type}};function Lb(b,d,c){if(q(d))(d=Mb(b,d))&&(b.style[d]=c);else for(var e in d){c=b;var f=d[e],g=Mb(c,e);g&&(c.style[g]=f)}}var Nb={};function Mb(b,d){var c=Nb[d];if(!c){var e=xa(d),c=e;void 0===b.style[e]&&(e=(La?"Webkit":Ka?"Moz":z?"ms":Ia?"O":null)+ya(e),void 0!==b.style[e]&&(c=e));Nb[d]=c}return c};function V(b){this.h=b;this.c=this.a=this.b=null;window.addEventListener("resize",this.g.bind(this),!1)}function W(b){if(!b.c){var d=b.m();d&&(b.b||(b.b=db("DIV"),Lb(b.b,"position","relative"),fb(d,b.b),b.g()),b.a||(b.a=db("CANVAS"),Lb(b.a,"position","absolute"),Lb(b.a,"top",0),Lb(b.a,"left",0),fb(b.b,b.a),b.g()),b.c||(b.c=b.a.getContext("2d")))}return b.c}V.prototype.m=function(){return this.h||document.body};V.prototype.getTarget=V.prototype.m;
V.prototype.s=function(){if(!window)throw Error("Window name space is not available!");window.draw={circle:this.C.bind(this),clear:this.clear.bind(this),ellipse:this.ellipse.bind(this),image:this.F.bind(this),line:this.I.bind(this),point:this.J.bind(this),rectangle:this.K.bind(this),text:this.text.bind(this),triangle:this.M.bind(this)}};V.prototype.mapGlobal=V.prototype.s;function X(b){if(q(b)&&!/^[\s\xa0]*$/.test(null==b?"":String(b)))return b}
V.prototype.C=function(b,d,c,e,f,g){var h=W(this),k=Y(e);if(!k.b){if(e=X(e))k.c=new T(e);f&&U(k,f);g&&(k.a=g)}return Z(this,function(){h.arc(b,d,c||25,0,2*Math.PI,!1)},h,k)};V.prototype.circle=V.prototype.C;V.prototype.clear=function(){W(this).clearRect(0,0,this.a.width,this.a.height)};V.prototype.clear=V.prototype.clear;V.prototype.I=function(b,d,c,e,f,g){var h=W(this),k=Y(f);k.b||((f=X(f))?U(k,f):U(k,"#000"),k.a=g?g:1);return Z(this,function(){h.moveTo(b,d);h.lineTo(c,e)},h,k)};
V.prototype.line=V.prototype.I;V.prototype.K=function(b,d,c,e,f,g,h){var k=W(this),n=Y(f);if(!n.b){if(f=X(f))n.c=new T(f);g&&U(n,g);h&&(n.a=h)}return Z(this,function(){k.rect(b,d,c,e)},k,n)};V.prototype.rectangle=V.prototype.K;V.prototype.text=function(b,d,c,e,f,g){f=void 0===f?"24px serif":f;var h=W(this),k=Y(e);!k.b&&(e=X(e))&&(g?k.i=new T(e):k.g=new T(e));return Z(this,function(){h.font=f||"24px serif";g?h.strokeText(b,d,c):h.fillText(b,d,c)},h,k)};V.prototype.text=V.prototype.text;
V.prototype.F=function(b,d,c,e,f){var g=W(this),h=null;("string"==typeof b||b instanceof String)&&b.includes("data:")?(h=new Image,h.src=b):h=b;return Z(this,function(){e&&f?g.drawImage(h,d,c,e,f):g.drawImage(h,d,c)},g)};V.prototype.image=V.prototype.F;V.prototype.J=function(b,d,c,e){e=void 0===e?1:e;var f=W(this),g=Y(c);!g.b&&(c=X(c))&&(g.g=new T(c));return Z(this,function(){f.fillRect(b,d,e||1,e||1)},f,g)};V.prototype.point=V.prototype.J;
V.prototype.ellipse=function(b,d,c,e,f,g,h){var k=W(this),n=Y(f);if(!n.b){if(f=X(f))n.c=new T(f);g&&U(n,g);h&&(n.a=h)}g=c/2;var x=e/2,v=b-g,J=d-x,K=v+g,L=J+x,P=v+c,ua=J+e,ca=.5522847498*g,da=.5522847498*x;return Z(this,function(){k.moveTo(v,J+x);k.bezierCurveTo(v,L-da,K-ca,J,K,J);k.bezierCurveTo(K+ca,J,P,L-da,P,L);k.bezierCurveTo(P,L+da,K+ca,ua,K,ua);k.bezierCurveTo(K-ca,ua,v,L+da,v,L)},k,n)};V.prototype.ellipse=V.prototype.ellipse;
V.prototype.M=function(b,d,c,e,f,g,h,k,n){var x=W(this),v=Y(h);if(!v.b){if(h=X(h))v.c=new T(h);k&&U(v,k);n&&(v.a=n)}return Z(this,function(){x.moveTo(b,d);x.lineTo(c,e);x.lineTo(f,g);x.lineTo(b,d)},x,v)};V.prototype.triangle=V.prototype.M;function Z(b,d,c,e){if(!c)return b;e&&(c.beginPath(),e.g.f&&(c.fillStyle=e.g.f),e.i.f&&(c.strokeStyle=e.i.f));d.call(b);e&&(c.fillStyle=e.c.f?e.c.f:"#ccc",c.fill(),e.a&&(c.lineWidth=e.a),e.h.f&&(c.strokeStyle=e.h.f,c.stroke()),c.closePath());return b}
function Y(b){var d=new Kb;r(b)&&(d.b=!0,d.c=new T(b.backgroundColor),U(d,b.borderColor),d.a=b.borderSize,d.g=new T(b.fillStyle));return d}V.prototype.g=function(){this.a&&(this.a.width=window.innerWidth,this.a.height=window.innerHeight)};function Ob(){var b=new R,d=new V;b&&b.s();d&&d.s()}t("cwc.framework.simple.Loader.mapFramework",Ob);Ob();
