var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,f=0;f<d;f++){var e=a[f];if(b.call(c,e,f,a))return{i:f,v:e}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
var kproxyAgentId="",kproxyAgentDisabled=!1,kproxyAgentStarted=!1,userServers=null,ERROR_NO_CONNECTION=1,ERROR_LOGIN=2,IP_TYPE_PUBLIC=1,IP_TYPE_PRO=2,IP_TYPE_LOGIN=3,LOGO_INI=0,LOGO_FREE=1,LOGO_PRO=2,lastUIs=null,NO_PROXY_DB_SERVERS=["http://localhost/kproxy/api_kpa_userservers.jsp"],PROXY_DB_SERVERS="http://servers.request",WPAD="http://wpad/wpad.dat",CONNECTING_TO_SERVERS_MESSAGE="Connecting to KProxy Servers",AVAILABLE_FLAGS="us uk de ca fr nl sg".split(" "),loadingTimeout=null;
document.addEventListener("DOMContentLoaded",function(){uiStart();init()});function init(){kproxyAgentStarted=chrome.extension.getBackgroundPage().kproxyStarted;chrome.extension.getBackgroundPage().waitingFor407?uiShowLaunchProxyAuth():chrome.extension.getBackgroundPage().tryingServer?uiShowLoading(!0,CONNECTING_TO_SERVERS_MESSAGE):kproxyAgentStarted?(uiShowLoading(!0,CONNECTING_TO_SERVERS_MESSAGE),loadServersFromCurrent()):uiShowStartKProxy()}
function uiStart(){$("#disconnect").click(function(){stopKProxyAgent();uiShowStartKProxy()});$("#start").click(function(){startKProxyAgent()});$("#account_button").click(function(){chrome.extension.getBackgroundPage().kproxyStarted&&uiShowAccountTab()});$("#servers_tab").click(function(){uiShowServersTab()});$("#back_settings_button").click(function(){uiSettingsCancel()});$("#upgrade_container .upgrade_button").click(function(){openTabUpgrade()});$("#credits_container .get_more_credits").click(function(){openTabUpgrade()});
$("#upgrade_button").click(function(){openTabUpgrade()});$("#login_forgot").click(function(){openTab("http://kproxy.com/forgotpassword.jsp")});$("#login_new").click(function(){openTab("http://kproxy.com/privatenewuser.jsp")});$("#login_button").click(function(){login()});$("#account_login_button").click(function(){uiShowLogin()});$("#logout").click(function(){logout()});$("#account_create").click(function(){openTab("http://kproxy.com/privatenewuser.jsp")});$("#settings").click(function(){uiShowSettings()});
$("#settings_ok_button").click(function(){changeProxySettings()});$("#settings_cancel_button").click(function(){uiSettingsCancel()});$("input:radio[name ='settings_proxy_option']").change(function(){uiChangeProxySettingsSelection()});$("#error_connection_proxy_button").click(function(){openTab("help.html#kproxy_agent")});$("#error_login_button").click(function(){uiShowLogin()});$("#error_server_search_button").click(function(){startKProxyAgent()});$("#help").click(function(){openTab("help.html")});
$("#loading_proxy_insert_credentials").click(function(){chrome.extension.getBackgroundPage().launchProxyAuth()});$("#proxy_settings_help").click(function(){openTab("help.html#settings_configure")});$("#login_passwd").keypress(function(a){13==a.which&&(a.preventDefault(),login())});$("#login_user").keypress(function(a){13==a.which&&(a.preventDefault(),""!=$("#login_user").val()&&(""==$("#login_passwd").val()?$("#login_passwd").focus():login()))})}
function login(){uiShowLoading(!0,CONNECTING_TO_SERVERS_MESSAGE,!0);chrome.extension.getBackgroundPage().login($("#login_user").val(),$("#login_passwd").val(),function(a,b){a?b?uiShowLoginError():uiShowAccountTab():uiShowConnectionError()})}
function changeProxySettings(){var a=$("input:radio[name ='settings_proxy_option']:checked").val(),b={},c=!1;"auto"==a?b.pacFile="http://wpad/wpad.dat":"pac"==a?(b.pacFile=$("#settings_pac_file").val().trim(),0==b.pacFile.length?(uiShowTextFieldError($("#settings_pac_file"),"Fill the pac file location.<br>Example: http://domain.example/pacfile.dat"),c=!0):0!=b.pacFile.indexOf("http://")&&b.pacFile.indexOf("https://")&&(uiShowTextFieldError($("#settings_pac_file"),"Incorrect pac file location format.<br>Example: http://domain.example/pacfile.dat"),
c=!0)):(b.proxy=$("#settings_proxy_address").val(),0==b.proxy.length&&(uiShowTextFieldError($("#settings_proxy_address"),"Fill the proxy address."),c=!0),b.port=$("#settings_proxy_port").val(),0<b.port.length&&!isInt(b.port)&&(uiShowTextFieldError($("#settings_proxy_port"),"Port must be a number."),c=!0));c||(uiShowLoading(!1,"Saving proxy settings"),$("#settings").show(),chrome.extension.getBackgroundPage().stopKProxyAgentSignal(function(){chrome.extension.getBackgroundPage().setProxyConfiguration(b,
function(){uiShowStartKProxy()})}))}function isInt(a){return Math.floor(a)==a}function uiShowTextFieldError(a,b){a.focus();a.addClass("textFieldError");a.tooltipster("content",b);a.tooltipster("enable");a.tooltipster("show")}function startKProxyAgent(){uiShowLoading(!0,CONNECTING_TO_SERVERS_MESSAGE);chrome.extension.getBackgroundPage().checkKProxyAgentInstalled(function(){reloadServers()})}
function stopKProxyAgent(){chrome.extension.getBackgroundPage().stopKProxyAgentSignal();uiSetState("Disconnected","connect_off")}function uiSetState(a,b){37<a.length&&(a=-1<a.indexOf("...")?a.substring(0,35)+"...":a.substring(0,34)+"...");$("#connection_state").attr("class","removable connect "+b);$("#connection_state").html("[ "+a+" ]")}function uiShowStartKProxy(){uiCleanMainPanel();$("#disconnect").hide();$("#account_button").hide();$("#start").fadeIn();uiShowLogo(LOGO_INI)}
function uiShowLaunchProxyAuth(){uiCleanMainPanel();$("#disconnect").show();$("#loading_proxy").fadeIn();uiShowLogo(LOGO_INI)}function uiShowError(a){"login.error"==a?uiShowLoginError():uiShowReloadKProxyError()}function uiShowReloadKProxyError(){}function uiShowConnectionError(){console.trace();uiCleanMainPanel();chrome.extension.getBackgroundPage().kproxyStarted?$("#disconnect").show():$("#disconnect").hide();$("#error").fadeIn();$("#error_connection").show()}
function uiShowLoginError(){chrome.extension.getBackgroundPage().user.login=null;chrome.extension.getBackgroundPage().user.passwd=null;uiCleanMainPanel();$("#error").fadeIn();$("#error_login").show()}function uiShowInstallAppError(){uiCleanMainPanel();$("#disconnect").hide();uiShowLogo(LOGO_INI);$("#error").fadeIn();$("#error_install").show()}function uiShowEnableAppError(){uiCleanMainPanel();$("#disconnect").hide();uiShowLogo(LOGO_INI);$("#error").fadeIn();$("#error_disabled").show()}
function uiShowLoading(a,b,c){b||(b="Doing some stuff");$("#loading_waiting_text").html("["+b+"]");uiCleanMainPanel();$("#loading_waiting").fadeIn();a?$("#disconnect").show():$("#disconnect").hide();loadingTimeout||($("#loading_task").html(""),changeLoadingState(a,c))}
function changeLoadingState(a,b){loadingTimeout=setTimeout(function(){var c=chrome.extension.getBackgroundPage().tryingServer;null!=c?(c.name&&$("#loading_task").html("Trying server "+c.name+"..."),changeLoadingState(a)):a&&loadServers(b)},1E3)}function uiShowAccountTab(){chrome.extension.getBackgroundPage().kproxyStarted?(uiCleanMainPanel(),$("#servers_tab").show(),$("#disconnect").hide(),$("#account_button").hide(),$("#account").fadeIn(),uiShowAccount()):uiShowStartKProxy()}
function uiShowServersTab(){chrome.extension.getBackgroundPage().kproxyStarted&&(uiCleanMainPanel(),$("#servers_tab").hide(),$("#disconnect").show(),$("#account_button").show(),$("#settings").show(),$("#connection_state").show(),$("#servers").fadeIn(),uiShowServers())}
function uiShowLogin(){uiCleanMainPanel();$("#servers_tab").show();$("#login").fadeIn();var a=chrome.extension.getBackgroundPage().user;null!=a.login&&0!=a.login.indexOf("*cookie_")?($("#login_user").val(a.login),$("#login_passwd").val(a.passwd)):($("#login_user").val(""),$("#login_passwd").val(""))}
function uiShowSettings(){uiSaveLastUIShown();uiCleanMainPanel();$("#settings").hide();$("#account_button").hide();$("#back_settings_button").show();$("#disconnect").hide();var a=chrome.extension.getBackgroundPage().proxySettings;a.proxy?($("input:radio[name ='settings_proxy_option'][value='proxy']").attr("checked","checked"),$("#settings_proxy_address").val(a.proxy),a.port&&$("#settings_proxy_port").val(a.port)):null==a.pacFile||a.pacFile==WPAD?$("input:radio[name ='settings_proxy_option'][value='auto']").attr("checked",
"checked"):a.pacFile&&($("input:radio[name ='settings_proxy_option'][value='pac']").attr("checked","checked"),$("#settings_pac_file").val(a.pacFile));uiChangeProxySettingsSelection();$("#proxy_settings").fadeIn()}function uiSettingsCancel(){uiCleanMainPanel();$("#settings").show();for(var a=0;a<lastUIs.length;a++)lastUIs[a].fadeIn()}function loadServersFromCurrent(){chrome.extension.getBackgroundPage().reloadServersFromCurrent(function(a){a?fillServers():uiShowConnectionError()})}
function loadServers(a){chrome.extension.getBackgroundPage().serverSearchFailed&&uiShowConnectionError()}function reloadServers(a){chrome.extension.getBackgroundPage().groupFilter=a;chrome.extension.getBackgroundPage().reloadServers(function(a){chrome.extension.getBackgroundPage().groupFilter=null;a?fillServers():uiShowConnectionError()})}
function fillServers(a,b){try{chrome.extension.getBackgroundPage();chrome.extension.getBackgroundPage();var c=chrome.extension.getBackgroundPage().currentServer;null!=c?a?uiSetState("Problem with "+c.name,"connect_ing"):uiSetState("Connected to "+c.name,"connect_on"):uiSetState("Disconnected","connect_off");b||uiShowServersTab()}catch(d){}}
function uiCleanMainPanel(){var a=chrome.extension.getBackgroundPage().user&&chrome.extension.getBackgroundPage().user.pro;chrome.extension.getBackgroundPage().defaultServersRemoved?uiShowLogo(a?LOGO_PRO:LOGO_FREE):uiShowLogo(LOGO_INI);loadingTimeout&&(clearTimeout(loadingTimeout),loadingTimeout=null);$(".removable").each(function(){$(this).hide()})}function uiSaveLastUIShown(){lastUIs=[];$(".removable").each(function(){$(this).is(":visible")&&lastUIs.push($(this))})}
function prepareGroups(a,b){for(var c=[],d=null,f=0;f<a.length;f++){var e=a[f],g=null;g=null!=d&&d.name==e.group?d:findGroup(c,e.group);null==g&&(g={},g.name=e.group,g.servers=[],c.push(g));g.servers.push(e);null!=b&&b.ip==e.ip&&(g.connected=!0);e.open&&(g.open=!0);d=g}c.sort(function(a,b){if(a.open!=b.open)return a.open?-1:1;a=a.name.toLowerCase();b=b.name.toLowerCase();return a<b?-1:a>b?1:0});return c}function findGroup(a,b){for(var c=0;c<a.length;c++)if(a[c].name==b)return a[c];return null}
function generateGroupHTML(a,b,c){for(var d="",f=0;f<a.length;f++){var e=a[f],g=null!=b&&b.ip==e.ip;d+='<div class="server_row '+(0<f?" separator":"")+' "><div class="server_info"><div class="server'+(g?" server_on":"")+'">'+(e.type==IP_TYPE_PRO?' <img src="img/star_gold.png">':"")+e.name+'</div><div class="load'+(g?" load_on":"")+'"><div class="bar'+(g?" bar_on":"")+'" style="width: '+e.load+'%"> </div><div class="text">'+e.load+'%</div></div></div><div class="server_button_container">';d=e.open?
c[e.ip]?d+('<div server_name="'+e.name+'" class="banned_button">Unban</div>'):d+('<div server_name="'+e.name+'" class="'+(g?"":"connect_button active_button ")+"button"+(g?" button_on":"")+(g?"":" sliding_bg")+'">'+(g?"Connected":"<span>Connect</span>")+"</div>"):d+'<div class="lock unlock_upgrade"><img src="img/lock.png" title="upgrade to PRO account to unlock"></div>';d+="</div></div>"}return d}
function getFlagURL(a){a=a.flag;return-1!=AVAILABLE_FLAGS.indexOf(a)?"img/flag_"+a+".png":"http://kproxy.com/img/flag_"+a+".png"}function convertToId(a){return a.replace(/ /g,"_")}function saveState(){var a=[];$(".server_list_container").each(function(){$(this).is(":hidden")||a.push($(this).attr("id"))});return a}function recoverState(a){if(null!=a)for(var b=0;b<a.length;b++)$("#"+a[b]).show(),$("#"+a[b]+"_button").find(".plus_icon").hide(),$("#"+a[b]+"_button").find(".minus_icon").show()}
function uiShowServers(){var a=chrome.extension.getBackgroundPage().user&&chrome.extension.getBackgroundPage().user.pro,b=chrome.extension.getBackgroundPage().servers,c=chrome.extension.getBackgroundPage().currentServer,d=chrome.extension.getBackgroundPage().serversBanned,f=saveState();$("#servers").empty();b=prepareGroups(b,c);var e=b.length;if(0!=e){for(var g=1<e,n=5<b.length?"_small":"",m=0;m<e;m++){var h=b[m],p=generateGroupHTML(h.servers,c,d);if(g){var k=h.servers[0],l=convertToId(h.name)+"_dropdown";
k='<div class="svr_dropbtn_container'+n+'"><div kproxy_group="'+h.name+'" class="servers_dropdown_button'+n+" "+(h.connected?" servers_dropdown_button_on":h.open?" active_button server_button_click":" servers_dropdown_button_lock")+'"><img src="'+getFlagURL(k)+'"><div class="text"><span class="bold">'+k.group+"</span>"+(h.connected?" Connected":"")+'</div><div class="group_connect_icon"><img class="connect_icon" src="../img/icon.png"></div></div>';k=h.open?k+('<div id="'+l+'_button" class="plus_button active_button"><img class="plus_icon" src="img/plus_icon.png"><img class="minus_icon" src="img/minus_icon.png"></div>'):
k+'<div class="plus_button plus_button_lock unlock_upgrade"><img src="img/lock.png" title="upgrade to PRO account to unlock"></div>';k+="</div>";$("#servers").append(k);$("#servers").append("<div id= "+l+' class="server_list_container"></div>');$("#"+l).append(p);$("#"+l+"_button").attr("dropdown",l);$("#"+l+"_button").click(function(){var a=$(this).attr("dropdown");$("#"+a).slideToggle();$(this).find(".plus_icon").toggle();$(this).find(".minus_icon").toggle()})}else $("#servers").append(p)}a||($("#servers").append('<div id="upgrade_button"><img src="img/upgrade.png"></div>'),
$("#upgrade_button").click(function(){openTabUpgrade()}));$(".server_button_click").each(function(){$(this).click(function(){var a=$(this).attr("kproxy_group");uiShowLoading(!0,CONNECTING_TO_SERVERS_MESSAGE);reloadServers(a)})});$(".connect_button").each(function(){$(this).click(function(){var a=this.getAttribute("server_name");uiSetState("Connecting to "+a+"...","connect_ing");$(this).addClass("button_ing");$(this).parent().addClass("button_ing");$(this).html("Connecting...");a=findServer(this.getAttribute("server_name"));
connectTo(a,function(a){uiShowServersTab()},1E4);return!1})});$(".unlock_upgrade").each(function(){$(this).click(function(){openTabUpgrade()})});$(".banned_button").each(function(){$(this).click(function(){this.getAttribute("server_name");var a=findServer(this.getAttribute("server_name"));unbanServer(a.ip);uiShowServersTab();return!1})});recoverState(f)}}
function uiShowAccount(){var a=chrome.extension.getBackgroundPage().user;$("#settings").hide();null==a.login||0==a.login.indexOf("*cookie_")?($("#user").hide(),$("#account_login").show(),$("#user_login").click(function(){uiShowLogin()}),$("#user_new").click(function(){openTab("http://kproxy.com/privatenewuser.jsp")})):($("#account_login").hide(),$("#user").show(),$("#user_name").html("welcome <span>"+a.login+"!</span>"));a.pro?($("#usage_container").hide(),$("#usage_container_pro").show(),$("#credits_left").html(a.credits+
" <span>credits left</span>")):($("#usage_container").show(),$("#usage_container_pro").hide(),$("#usage_transfer .text").html(bytesToMB(a.transfer>a.maxTransfer?a.maxTransfer:a.transfer)+"MB transferred"),$("#usage_transfer .bar_container").show(),a=calculatePercentage(a.transfer,a.maxTransfer),$("#usage_transfer .bar_container .bar").width(a+"%"),100==a&&$("#usage_transfer .bar_container .bar").addClass("redbar"))}
function uiShowLogo(a){a==LOGO_FREE?$("#logo").attr("src","img/kproxy_free.png"):a==LOGO_PRO?$("#logo").attr("src","img/kproxy_pro.png"):a==LOGO_INI&&$("#logo").attr("src","img/kproxy.png")}function millisecondsToMinutes(a){return Math.round(a/1E3/60)}function bytesToMB(a){return Math.round(a/1E3/1E3)}function calculatePercentage(a,b){return Math.min(Math.round(100*a/b),100)}function openTab(a){chrome.tabs.create({url:a})}
function openTabUpgrade(){var a="http://kproxy.com/upgrade.jsp",b=chrome.extension.getBackgroundPage().user;null!=b.login&&-1==b.login.indexOf("*cookie_")&&(a="http://kproxy.com/submit.jsp?login="+b.login+"&passwd="+b.passwd+"&action=LoginJSPAction&page=upgrade.jsp");openTab(a)}function logout(){$("#login_user").val("");$("#passwd_user").val("");login()}function findServer(a){for(var b=chrome.extension.getBackgroundPage().servers,c=0;c<b.length;c++)if(b[c].name==a)return b[c];return null}
function bringConnectedToTop(a,b){var c=0;if(null!=b)for(;c<a.length&&a[c].ip!=b.ip;c++);c<a.length&&(b=a[c],a.splice(c,1),a.splice(0,0,b))}function connectTo(a,b,c){uiShowLoadingPopup();chrome.extension.getBackgroundPage().connectTo(a,function(c){uiHideLoadingPopup();c?(uiSetState("Connected to "+a.name,"connect_on"),b(!0)):(uiShowConnectToErrorPopup(a),uiSetState("Disconnected","connect_off"),b(!1))},!0,c)}
function uiShowLoadingPopup(){$("body").prepend("<div id='loading'><img id='loading_icon' src='img/loading.gif'></div>");$("#loading").css({width:$(document).width(),height:$(document).height()});$("#loading_icon").css({top:""+($(window).height()/2-$("loading_icon").height()/2)+"px",left:""+($(window).width()/2-$("#loading_icon").width()/2)+"px"});$("#loading").fadeIn()}function uiHideLoadingPopup(){$("#loading").stop();$("#loading").fadeOut(function(){$("#loading").remove()})}
function uiShowConnectToErrorPopup(a){$("body").prepend('<div id="popup"><div id="connectTo_error"><div class="error_oops">oops!</div><div class="error_logo"><img src="img/error.png"></div><div class="error_title">[ <span>Could not connect to server!</span> ]</div><div class="error_desc"><div><span class="solution">Mark server '+a.name+' as banned?</span></div><div><div class="button_white_large" id="error_pop_server_banned_button">Ban server <img src="img/ban.png"></div></div><div class="gap"></div><div><span class="solution">Automatic server search</div><div><div class="button_white_large" id="error_pop_server_search_button">Search <img src="img/search.png"></div></div><div class="control_button"><div class="blue_button" id="error_pop_close_button">close</div></div><div class="clear"></div></div></div></div>');
$("#error_pop_close_button").click(function(){uiHideConnectToErrorPopup()});$("#popup").click(function(){uiHideConnectToErrorPopup()});$("#error_pop_server_banned_button").click(function(){uiHideConnectToErrorPopup();banServer(a.ip);uiShowServersTab()});$("#error_pop_server_search_button").click(function(){uiHideConnectToErrorPopup();startKProxyAgent()});$("#popup").css({width:$(document).width(),height:$(document).height()});$("#popup").fadeIn()}
function uiHideConnectToErrorPopup(){$("#popup").stop();$("#popup").fadeOut(function(){$("#popup").remove()})}function banServer(a){chrome.extension.getBackgroundPage().banServer(a)}function unbanServer(a){chrome.extension.getBackgroundPage().unbanServer(a)};
